version: 2

jobs:
  build:
    docker:
      - image: cimg/node:12
    working_directory: ~/shifter-support-plugin
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run:
          name: ESLINT
          command: ./node_modules/.bin/eslint *.js ./assets/
      - run: sudo yarn build:production
      # Check change but not built.
      - run:
          name: IS_DIST_NEWEST
          command: git diff --check --exit-code || { echo "Diff detected! please check dist was synced."; git status ; exit 1; }
      - run:
          name: VERSION_CHECK
          command: if ! [ `cat package.json | jq -r  .version` == `cat shifter-support-plugin.php | grep Version | cut -f 2 -d ' '` ] ; then exit 1 ; fi
